### ISSUE TITLE
No module named bs4

### ISSUE THREAD

**Issue by ghost** [Aveek-Saha/Movie-Script-Database#4]
Got the following error running get_scripts.py for the first time Any suggestions?

Traceback (most recent call last):
  File "/home/david/Movie-Script-Database/get_scripts.py", line 1, in <module>
    import sources
  File "/home/david/Movie-Script-Database/sources/__init__.py", line 1, in <module>
    from .imsdb import get_imsdb
  File "/home/david/Movie-Script-Database/sources/imsdb.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by ghost** [comment]
Just needed to run "pip install beautifulsoup4"
